import React from 'react';

export interface CRBPayQRProps {
    /**
     * Account Abstraction address or Wallet address
     */
    address: string;
    /**
     * Chain ID for the payment
     */
    chainId: number | string;
    /**
     * Amount to be paid
     */
    amount: number | string;
    /**
     * Use sandbox environment
     * @default false
     */
    isSandbox?: boolean;
    /**
     * Custom CSS class for the img tag
     */
    className?: string;
    /**
     * Alt text for the image
     * @default "CRBPay QR"
     */
    alt?: string;
    /**
     * Custom base URL for the QR service
     */
    baseUrl?: string;
}

/**
 * CRBPayQR Component
 * 
 * Displays a payment QR code image generated by CRBPay QR service.
 * Supports both production and sandbox environments.
 */
export const CRBPayQR: React.FC<CRBPayQRProps> = ({
    address,
    chainId,
    amount,
    isSandbox = false,
    className = "w-[240px] h-[240px] object-contain",
    alt = "CRBPay QR",
    baseUrl,
}) => {
    const [loading, setLoading] = React.useState(true);
    const [error, setError] = React.useState(false);

    // Construct the base URL based on environment or provided override
    const finalBaseUrl = baseUrl || (isSandbox
        ? 'https://sandbox-qr.crbpay.com'
        : 'https://qr.crbpay.com');

    // Format amount to ensure it's a number (stripping any non-numeric chars if string)
    const numAmount = typeof amount === 'string' ? parseFloat(amount) : Number(amount);

    // Construct the final image URL
    const imageUrl = `${finalBaseUrl}/${address}-${chainId}-${numAmount}.png`;

    if (!address || !chainId || isNaN(numAmount)) {
        return <div className={className} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#f4f4f5', borderRadius: '8px' }}>Invalid Parameters</div>;
    }

    return (
        <div style={{ position: 'relative', display: 'inline-block' }} className={className}>
            {loading && !error && (
                <div style={{
                    position: 'absolute',
                    inset: 0,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    background: 'rgba(255,255,255,0.8)',
                    zIndex: 1
                }}>
                    {/* Simple CSS Loader */}
                    <div className="crb-qr-loader" style={{
                        width: '24px',
                        height: '24px',
                        border: '3px solid #f3f3f3',
                        borderTop: '3px solid #3498db',
                        borderRadius: '50%',
                        animation: 'spin 1s linear infinite'
                    }} />
                    <style>{`
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
          `}</style>
                </div>
            )}

            {error ? (
                <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    height: '100%',
                    background: '#fee2e2',
                    color: '#b91c1c',
                    fontSize: '12px',
                    textAlign: 'center',
                    padding: '10px',
                    borderRadius: '8px'
                }}>
                    Failed to load QR
                </div>
            ) : (
                <img
                    src={imageUrl}
                    alt={alt}
                    style={{ width: '100%', height: '100%', objectFit: 'contain' }}
                    onLoad={() => setLoading(false)}
                    onError={() => {
                        setLoading(false);
                        setError(true);
                        console.error("Failed to load CRBPay QR image", imageUrl);
                    }}
                />
            )}
        </div>
    );
};

export default CRBPayQR;
